### ISSUE TITLE
Time format doesn't accept all possible hours

### ISSUE THREAD

**Issue by madb1lly** [tim-hellhake/scheduler-adapter#1]
Hello @tim-hellhake,
Thanks for making this scheduler add-on 😃 

The time fields don't accept any times where b>3 in ab:cd format. The errors in the config screen are: 
>     .schedules[0].periods[0].begin should match pattern "^[0-2][0-3]:[0-5][0-9]$"
>     .schedules[0].periods[0].end should match pattern "^[0-2][0-3]:[0-5][0-9]$" 

I'm not sure exactly which regex will work for this add-on but there's a discussion and several options proposed here: https://stackoverflow.com/questions/7536755/regular-expression-for-matching-hhmm-time-format

Cheers 🙂

**Comment by tim-hellhake** [comment]
> Thanks for making this scheduler add-on

Your welcome!

> The time fields don't accept any times where b>3 in ab:cd format

Indeed, that should be possible 😄.

> I'm not sure exactly which regex will work for this add-on but there's a discussion and several options proposed here

I went for the option `HH:MM 24-hour format, optional leading 0`.

**Comment by tim-hellhake** [comment]
@madb1lly
The update is out now.

**Comment by madb1lly** [comment]
Hi @tim-hellhake,
Thanks for the update. I set up two schedules and they are currently working fine. I'll raise another issue if there are any problems.
Cheers :)
